version: '3.8'

services:
  frontend:
    container_name: weather-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend

  backend:
    container_name: weather-backend
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6381
    depends_on:
      redis:
        condition: service_healthy

  redis:
    container_name: weather-redis
    image: redis:7-alpine
    ports:
      - "6381:6381"
    command: redis-server --port 6381
    volumes:
      - ./redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6381", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  cassandra:
    container_name: weather-cassandra
    build:
      context: db/cassandra
      dockerfile: Dockerfile
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=WeatherForecastCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=SimpleSnitch
      - CASSANDRA_SEEDS=cassandra
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra
    volumes:
      - ./cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-u", "cassandra", "-p", "cassandra", "-e", "describe keyspaces"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  model:
    container_name: weather-model
    build:
      context: .
      dockerfile: model/Dockerfile
    volumes:
      - ./model:/app/model
    environment:
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra
    depends_on:
      cassandra:
        condition: service_healthy

volumes:
  redis_data:
  cassandra_data: 